services:
    # Postgres Exporter
    postgres-exporter:
        image: prometheuscommunity/postgres-exporter:latest
        restart: on-failure
        environment:
            DATA_SOURCE_NAME: "postgresql://posthog:posthog@db:5432/posthog?sslmode=disable"
        ports:
            - "9187:9187"
        depends_on:
            db:
                condition: service_healthy

    # Expose ClickHouse built-in Prometheus metrics port
    clickhouse:
        ports:
            - "9116:9363"

    # Redis Exporter
    redis-exporter:
        image: oliver006/redis_exporter:latest
        restart: on-failure
        environment:
            REDIS_ADDR: "redis://redis7:6379"
        ports:
            - "9121:9121"
        depends_on:
            redis7:
                condition: service_healthy

    # Expose Redpanda metrics port
    kafka:
        ports:
            - "9644:9644"
